# Generated by Django 4.0.6 on 2022-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='describe',
            field=models.CharField(default='Null', max_length=1000),
        ),
    ]
